apiVersion: v1
kind: Service
metadata:
  name: site
  namespace: wordpress
  labels: { app: site }
spec:
  type: NodePort
  selector:
    app: site
    version: legacy   # 🔴 Commence par pointer sur legacy
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30095

