controller:
  adminUser: admin
  adminPassword: admin123
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
    - blueocean
    - credentials-binding
    - matrix-auth
    - docker-workflow
  serviceType: ClusterIP
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"
